remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/logo.png"
footer_content: "Online Linguistics Teaching &copy; 2020. Distributed with {% link license.md %} Creative Commons Attribution Share Alike 4.0 International Licence"
